---
title: Auch Rmarkdown Dateien sollten sich Regeln halten
author: Norman Markgraf
date: '2018-05-02'
slug: auch-rmarkdown-dateien-sollten-sich-regeln-halten
categories:
  - Allgemeines
  - Information
tags:
  - R
  - Allgemein
  - RMarkdown
  - Python
header:
  caption: ''
  image: ''
---

Jede Programmiersprache hat Regeln.
Neben dem Regelwerk welches durch den Syntax einer Sprache festgelegt wird, gib es aber noch Regeln über die Form, in der man den Quelltext schreibt.
Diese sogenannte *Stilregeln* (engl. *style guides*) sind von Programmieren aufgestellte Regeln um ein einheitliches "Schriftbild" des Quelltextes zu erhalten.
Das Ziel der *Stilregeln* ist es, den Quelltext lesbarer zu gestallten, um leichter Änderungen einzupflegen oder um unnötiges zu vermeiden.

Eine Programmiersprache wie Python zum Beispiel hat mit [PEP8](https://www.python.org/dev/peps/pep-0008/) einen eigenen Standard wie ein Python Programm geschrieben seien sollte. 
Dazu gibt es auch gleich das passenden Prüfprogramm (pep8, neuerdings [pycodestyle](https://github.com/PyCQA/pycodestyle)).

Schreibt man ein Rmarkdown Text mag man vielleicht nicht daran denken, dass so eine Idee auch hier sehr sinnvoll sein kann. 
Neben den gängigen Style-Guides für den R Quellcode (Z.B.: [Google's R Style Guide](https://google.github.io/styleguide/Rguide.xml), [Hadley Wickham's Advanced R - Style guide](http://adv-r.had.co.nz/Style.html), [jef.works R Style Guide](http://jef.works/R-style-guide/), [R Style Guide](https://csgillespie.wordpress.com/2010/11/23/r-style-guide/) oder [R-Style-Guide](https://github.com/rdatsci/PackagesInfo/wiki/R-Style-Guide)) gibt es aber kaum Regeln für die Gestaltung von Rmarkdown.


## Stil-Regeln für gutes Rmarkdown, ein erster Vorschlag

1. Keine unnützen Zeichen am Ende von Textzeilen. / *No whitespaces at the end of a line*
    
    Eine Textzeile sollte mit einem 'echtem' Zeichen enden und nicht mit einem 'unsichtbarem' Zeichen.
    Das heisst: Leerzeichen, Tabs, harte Leerzeichen etc. gehören nicht ans Ende einer Zeile.
    
2. Zwei Leerzeilen vor einer Kopfzeile. / *Two blank lines before a header*
    
    Um die Inhalte auch klar voneinander trennen zu können sollte man vor der Kopfzeile zwei Leerzeilen eingefügt werden.
    Statt
    
    ```
    # Das ist eine Kopfzeile auf der 1. Ebene
    ## Das is eine Kopfzeile auf der 2. Ebene
    Das hier ist einfacher Text
    ```
    
    sollte es so gegliedert sein:

    ```
    
    
    # Das ist eine Kopfzeile auf der 1. Ebene
    
    
    ## Das is eine Kopfzeile auf der 2. Ebene
    
    Das hier ist einfacher Text
    ```

3. Vor und nach Aufzählungen sollte immer eine Leerzeile stehen. / *...*
   
   Statt
   
   ```
   Das ist eine Liste:
   - Ein Punkt
   - Ein anderer Punkt
   Und hier geht der Text weiter.
   ```
   
   sollte es so gegliedert sein:
   
   ```
   Das ist eine Liste:

   - Ein Punkt
   - Ein anderer Punkt

   Und hier geht der Text weiter.
   ```
   
4. Vor und nach Codeblöcken sollte immer eine Leerzeile stehen. / *...*

   Statt
   
   ```
   Etwas Text vorher
   `` `{r}
   1+1
   `` `
   und danach.
   ```
   
   sollte es so gegliedert sein:
   
   ```
   Etwas Text vorher
   
   `` `{r}
   1+1
   `` `
   
   und danach.
   ```
   
5. Keine anderen Sprachen als Rmarkdown für Inhalte oder Design nutzen. / *Use no other languages to create content or design, other than (R)Markdown.*

   Keine anderen Sprachen, insbesondere LaTeX, um besondere Effekte zu erziehlen. Dafür sollten DIV oder SPAN Abschnitte benutzt werden.


## RmdStyleChecker, ein erster Style Checker für Rmarkdown

Die ersten drei Punkte der Liste habe ich zu Testzwecken in einem kleinen Projekt mit Hilfe von Python implementiert.
Den Python-Quelltext findet man unter [RmdStyleChecker](https://github.com/NMarkgraf/RmdStyleChecker). Er läuft unter Python 3.5+.

