---
title: "Der Satz von Vieta und Dr. Loh's Methode"
author: "admin"
date: '2020-02-26'
categories: Mathematik
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
lastmod: '2020-02-26T08:36:09+01:00'
projects: []
slug: der-satz-von-vieta-und-dr-loh-s-methode
subtitle: ''
summary: ''
tags:
  - Quadratische Gleichung
  - Satz von Vieta
  - Dr. Loh's Methode
authors: []
math: yes
---
 

Das schnelle Lösen von quadratischen Gleichungen -- mit ganzzahligen Lösungen -- ist etwas für den (Wurzel-)Satz von Vieta.

Ist eine quadratischen Gleichung in Normalform, genügt sie der Darstellung:

$$x^2 + px + q = 0$$

Diese Gleichung hat, wenn überhaupt, zwei Lösungen $x_1$ und $x_2$.

Wegen

$$(x-x_1) \cdot (x-x_2) = x^2 -(x_1+x_2)\cdot x + x_1\cdot x_2 = x^2 + px + q$$

muss somit $p = -\left(x_1+x_2\right)$ und gleichzeitig $q = x_1 \cdot x_2$ gelten. 

Sucht man nach (ganzzahligen) $x_1$ und $x_2$, so nimmt man die Teilermenge $T_q$ von $q$ und prüft für jedes $x \in T_q$ ob es ein $y \in T_q$ gibt, so dass $\pm x$ und $\pm y$ sowohl die Gleichungen für $p$ und $q$ erfüllen. Ein für $q$ passendes Paar zu finden ist dabei nicht das Problem. Aber die Gleichung für $p$ muss auch erfüllt sein. 

### Ein Beispiel

Hat die Gleichung $x^2 - 8 \cdot x + 12 = 0$ also nur ganzzahlige Lösungen, so reicht es die Teiler von $12$ zu untersuchen.
Nun ist $12 = 2 \cdot 2 \cdot 3$ und somit die Teilermenge von $12$ die Menge $T_{12} = \{1, 2, 3, 4, 6, 12\}$. 

Wegen der $p=-8$ muss $x_1 + x_2$ eine positive Zahl sein und wegen $q=+12$ müssen $x_1$ und $x_2$ somit auch beide positiv sein.

Gesucht ist also die Lösung von $x_1+x_2 = 8$ für $x_1, x_2 \in T_{12}$.

Für $1$ findet sich $12$, für $2$ findet sich $6$ und für $3$ findet sich $4$. Danach drehen sich die Positionen nur noch um.

Weil $1 + 12 = 13 \neq 8$ und $3+4=7 \neq 8$ ist fallen diese Paate leider als Lösungen aus.

Da $2+6=8$ und $2 \cdot 6 = 12$ ist, haben wir mit $x_1=2$ und $x_2=6$ eine Lösung gefunden.


### Dr. Loh's Methode

**Dr. Loh's Methode** zielt darauf ab, das Raten des Lösungspaars $x_1$ und $x_2$ etwas stärker in eine Berechnung zu überführen.

Wir starten mit $p=8$ und wissen, dass dies in die Summe von zwei Zahlen zerlegt werden muss. $p/2$ ist der Scheitelpunktsstelle der quadratischen Funktion $f(x) = x^2+px+q$ und die zwei Nullstellen, sofern existent, haben von der Scheitelpunktsstelle $p/$ den selben Abstand, den wir $u$ nennen wollen.

Damit ist

$$x_1 = \frac{p}{2} +u \quad\text{ und }\quad x_2 = \frac{p}{2} - u$$

In unserem Beispiel also
$$x_1 = 4+u \quad\text{ und }\quad x_2 = 4 - u$$
Da nachdem Wurzelsatz von Viete $q=x_1 \cdot x_2$ ist gilt (mit der 3. Binomischen Formel) für unser Beispiel nun

$$x_1 \cdot x_2 = (4+u)(4-u)=4^2-u^2 = 16-u^2 = 12$$

Wir stellen die Gleichung um und erhalten

$$u^2 = 16-12 = 4$$
woraus sich

$$u = \pm\sqrt{4} = \pm 2$$

und -- entweder durch ausprobieren oder nachdenken -- die Lösung $x_1=2$ und $x_2=6$ ergibt.


### Ein weiteres Beispiel

$$x^2 -10 \cdot x + 24 = 0$$

Dann ist $x_1=5-u$, $x_2=5+u$, $x_1\cdot x_2=25-u^2 = 24$ und somit $u^2=\pm 1$ und die Lösung $x_1=4$ sowie $x_2=6$. 


### Und noch ein Beispiel

$$x^2 - 7 \cdot x + 12 = 0$$

Nun ist $x_1=3{,}5-u$, $x_2=3{,}5+u$, $x_1 \cdot x_2 = 12{,}25-u^2=12$ und somit $u^2=\pm 0{,}25$ und die Lösung $x_1=3$ und $x_2=4$.

